plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/services/**/*'
    - 'spec/models/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/services/**/*'
    - 'spec/models/**/*'

RSpec/NestedGroups:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/services/**/*'
    - 'spec/models/**/*'
