apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moviedb.fullname" . }}
  labels:
    {{- include "moviedb.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secrets.database.password | quote }}
  KAFKA_USERNAME: {{ .Values.kafka.username | quote }}
  KAFKA_PASSWORD: {{ .Values.kafka.password | quote }}
  RAILS_MASTER_KEY: {{ .Values.secrets.rails.master_key | quote }}
  SECRET_KEY_BASE: {{ .Values.secrets.rails.secret_key_base | quote }}
