apiVersion: v1
kind: Service
metadata:
  name: {{ include "moviedb.fullname" . }}
  labels:
    {{- include "moviedb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "moviedb.selectorLabels" . | nindent 4 }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
