apiVersion: v1
kind: Service
metadata:
  name: {{ include "moviedb.kafka.headless" . }}
  labels:
    {{- include "moviedb.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  clusterIP: None
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
  selector:
    {{- include "moviedb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
