apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "moviedb.fullname" . }}-db-migrate
  labels:
    {{- include "moviedb.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "moviedb.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "scripts/migrate.js"]
          envFrom:
            - configMapRef:
                name: {{ include "moviedb.fullname" . }}-env
            - secretRef:
                name: {{ include "moviedb.fullname" . }}
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.secrets.database.username }}:{{ .Values.secrets.database.password }}@postgres-postgresql.database:5432/moviedb_production
