secrets:
    database:
        username: ENC[AES256_GCM,data:1O2me3M4Yj4=,iv:T1kZTRxIi5EUG2PBI6i234kvJqdOX5kZHPEdahC+mRk=,tag:C7m6kGRv1NpmEMBzC3ZUEA==,type:str]
        password: ENC[AES256_GCM,data:0e6c2ZQXUR/LqQ==,iv:AkWTqMSeRFhdqiIENXB5fLA4JLJLmdLktd/dTGWdhOc=,tag:BZzpha9DxY/6kFO2y5ewxw==,type:str]
    rails:
        master_key: ENC[AES256_GCM,data:EZsu0IT4fWnm2gU866Re6ARt2Y506w44dta4XNlS2Fw=,iv:NkzKxWjFym2nC68F4+qa+1ArJP2iuV+eZ6290eNZjdc=,tag:i+c0oW49CEt7ixR6lQ5eFA==,type:str]
        secret_key_base: ENC[AES256_GCM,data:79Gfq3EdD4LfTOMIelaDz2XVvXyEwjAOoB9TTkgzUewoMp4O2KStt7irnCyB1tEPvFgXYyR+Dzg3wWkKbObSOCF0NsfCgmq0p8hnhdf6zJX9FggZaTaWf+hk8KM9jRSW7qkTfDZp13AUwiA4UwrG77/5X9aBcT8EfXRTW8u2YyM=,iv:AbgNJG5o96bFAGIfpJEaOpooxeWSso6zFPNi/WhVv+w=,tag:b5/LyU/DqE85LQepbBsR/w==,type:str]
    kafka:
        username: ENC[AES256_GCM,data:0K+wCf8=,iv:qo7eI5PaHN/BO0il3exe78Hg36fE6sVolkAe5EhVJ8I=,tag:ueuiWcWkTryuIO2BkWqebw==,type:str]
        password: ENC[AES256_GCM,data:WHzD+uKQiMpL,iv:z96GPowNJblK8tWpUA+/sxDE4pdNtZERC61CTtrkcOY=,tag:RJ5jmBvLQIsPMcEd68ASfw==,type:str]
sops:
    age:
        - recipient: age1q8fe585fa09xk7d2nkau77y5seyvaduqc28lmfw93cw7yrwthgwqyltpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud000c2REbno5Q3F4cXR2
            Q1dwY3R3T1RtdVdXZ1RYa2hMcDZXQ3VJa0E0Ck4wTm1welY2Y1BCcUR3Uno3aU9k
            S2ZKSDROSWFvd2FEdjk0Q0hrcmYyUHMKLS0tIDNzcXoyYlhQMUFFSVNLSmdYTlV2
            TUh0WDRXa3owYUh3b1owUFBCMkhKUUEK5SCx3rDK5l/Hiaumql3LkKPKIrbOhA3E
            SMWderKVlJFCHyPLFBSl28O/hg8KQQMT0gNgG9FZ5wPR2UbVIQYWWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T05:29:48Z"
    mac: ENC[AES256_GCM,data:xQe/8vyJ+frcqhOqZik6l0qteKvkZlHU+4XSTbIRhz1PICspdAJGgaRUry5ErO6iaNoOFxTKLKUvG4vgVGoB96yOeesQP+Qr38/1axdW/ONIthy0YN3FWYUS9Oz3lmMZfm/m4BNhGdbFf68y/Cb9fn+EzT0d5LitlSJldyfH5M0=,iv:dsQ6a3jk3VQQltzS55GEb/Lx2e71F/N5ERUecdRCRmE=,tag:W6qcQMFvAY11zqS2OAZcGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
