FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
      libssl-dev \
      librdkafka-dev \
      git \
      curl \
      postgresql-client && \
    rm -rf /var/lib/apt/lists/*
