test:
  servers: "127.0.0.1:9160"
  keyspace: "moviedb_test"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  thrift:
    timeout: 3
    retries: 2

development:
  servers: "127.0.0.1:9160"
  keyspace: "moviedb_development"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  thrift:
    timeout: 3
    retries: 2
