apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moviedb.fullname" . }}-env
  labels:
    {{- include "moviedb.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.env.NODE_ENV | quote }}
  JELLYFIN_URL: {{ .Values.jellyfin.url | quote }}