apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "moviedb.fullname" . }}
  labels:
    {{- include "moviedb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "moviedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "moviedb.labels" . | nindent 8 }}
    spec:
      containers:
        - name: moviedb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "moviedb.fullname" . }}-env
            - secretRef:
                name: {{ include "moviedb.fullname" . }}
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.secrets.database.username }}:{{ .Values.secrets.database.password }}@postgres-postgresql.database:5432/moviedb_production
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
