apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moviedb.fullname" . }}
  labels:
    {{- include "moviedb.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secrets.database.password | quote }}
  DATABASE_USERNAME: {{ .Values.secrets.database.username | quote }}
  KAFKA_USERNAME: {{ .Values.secrets.kafka.username | quote }}
  KAFKA_PASSWORD: {{ .Values.secrets.kafka.password | quote }}
