apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviedb
  labels:
      app: moviedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviedb
  template:
    metadata:
      labels:
        app: moviedb
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
      - name: moviedb
        image: gitlab.pd.o:4567/drule/moviedb:10
        ports:
        - name: http
          containerPort: 3000
        envFrom:
          - configMapRef:
              name: moviedb
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: moviedb
              key: db-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moviedb
              key: db-password
