apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_USERNAME: {{ .Values.auth.username | quote }}
  KAFKA_PASSWORD: {{ .Values.auth.password | quote }}
  CLUSTER_ID: {{ .Values.auth.clusterId | quote }}
