secrets:
    database:
        username: ENC[AES256_GCM,data:1O2me3M4Yj4=,iv:T1kZTRxIi5EUG2PBI6i234kvJqdOX5kZHPEdahC+mRk=,tag:C7m6kGRv1NpmEMBzC3ZUEA==,type:str]
        password: ENC[AES256_GCM,data:0e6c2ZQXUR/LqQ==,iv:AkWTqMSeRFhdqiIENXB5fLA4JLJLmdLktd/dTGWdhOc=,tag:BZzpha9DxY/6kFO2y5ewxw==,type:str]
    tmdb_api_key: ENC[AES256_GCM,data:s9X74PTU52jHQB4/+equkuW0mS/IgK6G+88osJ7ixqo=,iv:Szl7vb2eANWSXNBW6JKorcM28rZQuHhhygP1VHTexOk=,tag:O7pGNKqwW7Caeu6E2g6UcA==,type:str]
    jellyfin_api_key: ENC[AES256_GCM,data:idp33Syohu+bEulT884gREFLsriYEJUeXDsqysAbI38=,iv:Y5zbh+Qov9guO4qIu6JeVQtY8QGpmWwNFMtpP/7QIpc=,tag:anDXqf6sAO9GrqkVpuzIvA==,type:str]
    smtp:
        user: ENC[AES256_GCM,data:qaQohdhMCUtv4Z1+Zw==,iv:T1uL8Q95i4VOPvIRGrAPobckefwTdpD0/JJXtQoJzCU=,tag:SQ+al39AbwmYW63baCyv7A==,type:str]
        password: ENC[AES256_GCM,data:VfEVPrxhs0EFjS7IUWpI2w==,iv:WDApRgbTd+/Q9cCqphptbgXrOg2yFVh4RAYWJ3hdoGE=,tag:cFhTzWoFhmJTHeY6AmbCKg==,type:str]
    cronSecret: ENC[AES256_GCM,data:/LR92nxs8ZiBUPEJqhaA,iv:3CbxV2TsQmov5h/ysmB0m7ek3ZCqDQP9an83QPajFmk=,tag:y64WzBVqjiedVstgfbHmxw==,type:str]
sops:
    age:
        - recipient: age1q8fe585fa09xk7d2nkau77y5seyvaduqc28lmfw93cw7yrwthgwqyltpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud000c2REbno5Q3F4cXR2
            Q1dwY3R3T1RtdVdXZ1RYa2hMcDZXQ3VJa0E0Ck4wTm1welY2Y1BCcUR3Uno3aU9k
            S2ZKSDROSWFvd2FEdjk0Q0hrcmYyUHMKLS0tIDNzcXoyYlhQMUFFSVNLSmdYTlV2
            TUh0WDRXa3owYUh3b1owUFBCMkhKUUEK5SCx3rDK5l/Hiaumql3LkKPKIrbOhA3E
            SMWderKVlJFCHyPLFBSl28O/hg8KQQMT0gNgG9FZ5wPR2UbVIQYWWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T08:59:08Z"
    mac: ENC[AES256_GCM,data:sQiYV1VCfUB1u8jUg+N0WHrZRPSX/WlWDAueZlXYHnyDYF6m9ZHwnEZa6W7vH4Bp2M0YdlpClnrLlt2LOYtlKBGVS79d/qnbXGMcEtK5rGhsFgfPed923FB5a3AMh8+Q4Nm2JdQ6aCfPG4fExU7Tr7QHzmT0TB2aBYIZFSFgHvw=,iv:WJRz6RMEitzOzLKpbbO8yDpnfIR32HAZp2GcGd5S1w8=,tag:Aow9RqJgMayoold46oB74A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
