secrets:
    database:
        username: ENC[AES256_GCM,data:1O2me3M4Yj4=,iv:T1kZTRxIi5EUG2PBI6i234kvJqdOX5kZHPEdahC+mRk=,tag:C7m6kGRv1NpmEMBzC3ZUEA==,type:str]
        password: ENC[AES256_GCM,data:0e6c2ZQXUR/LqQ==,iv:AkWTqMSeRFhdqiIENXB5fLA4JLJLmdLktd/dTGWdhOc=,tag:BZzpha9DxY/6kFO2y5ewxw==,type:str]
    tmdb_api_key: ENC[AES256_GCM,data:s9X74PTU52jHQB4/+equkuW0mS/IgK6G+88osJ7ixqo=,iv:Szl7vb2eANWSXNBW6JKorcM28rZQuHhhygP1VHTexOk=,tag:O7pGNKqwW7Caeu6E2g6UcA==,type:str]
    jellyfin_api_key: ENC[AES256_GCM,data:idp33Syohu+bEulT884gREFLsriYEJUeXDsqysAbI38=,iv:Y5zbh+Qov9guO4qIu6JeVQtY8QGpmWwNFMtpP/7QIpc=,tag:anDXqf6sAO9GrqkVpuzIvA==,type:str]
    smtp:
        user: ENC[AES256_GCM,data:qaQohdhMCUtv4Z1+Zw==,iv:T1uL8Q95i4VOPvIRGrAPobckefwTdpD0/JJXtQoJzCU=,tag:SQ+al39AbwmYW63baCyv7A==,type:str]
        pass: ENC[AES256_GCM,data:fbrkcWK2X3iVa64=,iv:gdZZPsiaydk3ZMQ4Zm5cKlhUOXNZYqxGXGeBgnxS6Ts=,tag:YUO4qq7+gOrrO2bH6ug9Lg==,type=str]
    cronSecret: ENC[AES256_GCM,data:CHANGE_ME_TO_REAL_SECRET,iv:placeholder,tag:placeholder,type:str]
sops:
    age:
        - recipient: age1q8fe585fa09xk7d2nkau77y5seyvaduqc28lmfw93cw7yrwthgwqyltpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud000c2REbno5Q3F4cXR2
            Q1dwY3R3T1RtdVdXZ1RYa2hMcDZXQ3VJa0E0Ck4wTm1welY2Y1BCcUR3Uno3aU9k
            S2ZKSDROSWFvd2FEdjk0Q0hrcmYyUHMKLS0tIDNzcXoyYlhQMUFFSVNLSmdYTlV2
            TUh0WDRXa3owYUh3b1owUFBCMkhKUUEK5SCx3rDK5l/Hiaumql3LkKPKIrbOhA3E
            SMWderKVlJFCHyPLFBSl28O/hg8KQQMT0gNgG9FZ5wPR2UbVIQYWWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T02:18:32Z"
    mac: ENC[AES256_GCM,data:HjtClyUThVJ2r9n1TkMft5QeE3HbF+WgF+UJ9FbOjT5RYh8ZtOY+lnIarPwGC3qlGEbfM3Dqt6G2ACZTTgdGv9jRFLt5Re1Zap0LOBkFDk1pUa0PJ4ADCW+GMk1rFOyYzHhuCslaXHpFwucVc+CNWc8JjX1qZ1OEXSqO1YTJycI=,iv:YSOcFLPD0zxXmf0+Ve/KTfErn6sml5LjLA1u2rEdfls=,tag:zyaxwDbnRj+AYJxWo5VZZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
